/* ============================================================
   LANGUAGE.JS — EN / AR Full Translation & RTL Support
   ============================================================ */

const translations = {
  en: {
    // Loading
    loadingTitle: "THE COLOSSEUM",
    loadingSubtitle: "Rome, Italy · The Eternal Arena",
    // Nav
    navHome: "Home",
    navHistory: "History",
    navArchitecture: "Architecture",
    nav3D: "3D Experience",
    navTimeline: "Timeline",
    navGladiators: "Gladiators",
    navGallery: "Gallery",
    navLocation: "Location",
    navFacts: "Facts",
    navSubtitle: "The Eternal Arena · Rome",
    navHypogeum: "Hypogeum",
    navMyth: "Myth vs. Fact",
    // Hero
    heroEyebrow: "Rome, Italy · 72–80 CE",
    heroSubtitle: "Anfiteatro Flavio · Rome",
    heroQuote: "Where the stones of Rome still remember the roar of history.",
    heroDesc: "One of the most iconic surviving monuments of ancient Rome — an elliptical amphitheatre commissioned under Emperor Vespasian, inaugurated under Titus, and a symbol of civilisation for nearly two millennia.",
    heroCTA1: "Explore the Colosseum",
    heroCTA2: "Enter 3D Experience",
    // Introduction
    introLabel: "The Monument",
    introTitle: "The Icon of Ancient Rome",
    introImageLabel: "Exterior · South Facade",
    introText1: "The Colosseum — also known as the Flavian Amphitheatre (Anfiteatro Flavio) — stands as one of the greatest engineering achievements of the ancient world. Commissioned by Emperor Vespasian around 72 CE and inaugurated by his son Titus in approximately 80 CE, it remains the largest amphitheatre ever built.",
    introText2: "For centuries, this massive structure hosted public spectacles — including gladiatorial contests, animal hunts (venationes), public performances, and reenactments of famous battles. Scholars estimate it could accommodate somewhere between 50,000 and 80,000 spectators across its tiered seating.",
    statConstruction: "Construction Began",
    statCapacity: "Est. Spectator Capacity",
    statHeight: "Original Height (approx.)",
    statLocation: "Italy 🇮🇹",
    // History
    historyLabel: "Through the Ages",
    historyTitle: "Two Thousand Years of History",
    historySubtitle: "From imperial spectacle to eternal monument",
    era1: "Construction",
    era2: "Inauguration",
    era3: "The Spectacles",
    era4: "Decline",
    era5: "Medieval Period",
    era6: "Modernity",
    hist1Title: "The Flavian Vision Begins",
    hist1Text: "Emperor Vespasian commissioned the Colosseum on the site of Nero's artificial lake, part of the Domus Aurea complex. Roman engineering — including travertine limestone, tuff, concrete (opus caementicium), and brick — combined in an unprecedented scale of construction.",
    hist2Title: "Titus Opens the Arena",
    hist2Text: "Emperor Titus inaugurated the Colosseum with approximately 100 days of games. Ancient sources describe elaborate spectacles. Emperor Domitian later added a fourth tier and the underground hypogeum.",
    hist3Title: "The Age of Spectacle",
    hist3Text: "For several centuries, the Colosseum hosted gladiatorial contests (munera), animal hunts (venationes), and public executions. These events were deeply embedded in Roman political and social life.",
    hist4Title: "Fire and Earthquake",
    hist4Text: "In 217 CE, a severe fire caused significant damage to the upper wooden tiers. Repairs were made, but recurring earthquakes — particularly those of 443 CE and later 1231 CE and 1349 CE — caused major structural damage.",
    hist5Title: "Repurposed Through the Ages",
    hist5Text: "After gladiatorial games ended, the Colosseum was used as a quarry for building materials, as a Christian shrine, as a fortress, workshops, and even housing at various points.",
    hist6Title: "From Ruin to World Heritage",
    hist6Text: "Beginning in the 18th century, preservation efforts grew. Pope Benedict XIV consecrated the site in the 1740s. Today it is a UNESCO World Heritage Site and one of the world's most visited landmarks.",
    // Timeline
    timelineLabel: "Key Dates",
    timelineTitle: "A Chronicle of the Colosseum",
    timelineSubtitle: "From foundation stone to world wonder",
    tl1Title: "Construction Begins",
    tl2Title: "Grand Inauguration",
    tl3Title: "Domitian's Additions",
    tl4Title: "Great Fire Damage",
    tl5Title: "Games Decline",
    tl6Title: "Earthquake Damage",
    tl7Title: "South Wall Collapse",
    tl8Title: "Papal Consecration",
    tl9Title: "UNESCO Heritage Site",
    tl10Title: "Eternal Monument",
    // Architecture
    archLabel: "Structure & Engineering",
    archTitle: "Masterwork of Roman Engineering",
    archSubtitle: "An ellipse of stone that redefined human ambition",
    archClickMsg: "Click the glowing hotspots on the diagram to explore individual architectural elements of the Colosseum.",
    af1Name: "Travertine Limestone",
    af1Text: "Approximately 100,000 cubic metres of travertine limestone was used in the outer structure, sourced from quarries near Tivoli and transported to Rome by road and river.",
    af2Name: "Elliptical Design",
    af2Text: "The elliptical shape — approximately 188m × 156m — allowed spectators throughout the arena to see the action clearly while preventing combatants from cornering themselves.",
    af3Name: "Vomitoria",
    af3Text: "An ingenious system of 80 numbered entrances and exit corridors (vomitoria) allowed the Colosseum to be filled or emptied of tens of thousands of spectators in approximately 15 minutes.",
    af4Name: "Roman Concrete",
    af4Text: "Opus caementicium (Roman concrete), combined with volcanic pozzolana, created extraordinarily durable structures. Modern analysis suggests this concrete may actually strengthen over time.",
    af5Name: "The Great Arches",
    af5Text: "The outer wall features three tiers of 80 arched openings, each decorated with engaged columns: Doric on the first level, Ionic on the second, and Corinthian on the third.",
    af6Name: "The Hypogeum",
    af6Text: "The two-level underground network used a system of winches, pulleys, and hinged platforms to raise animals and combatants dramatically into the arena.",
    // 3D
    threeLabel: "Interactive Experience",
    threeTitle: "3D Colosseum Experience",
    threeSubtitle: "Rotate · Zoom · Explore · Discover",
    threeLoading: "Building the arena…",
    threeExterior: "Exterior View",
    threeInterior: "Interior View",
    threeAerial: "Aerial View",
    threeReset: "Reset View",
    threeDragHint: "Drag to rotate · Scroll to zoom · Click hotspots",
    // Then & Now
    thenNowLabel: "Past & Present",
    thenNowTitle: "Then & Now",
    thenNowSubtitle: "Drag the divider to compare ancient Rome with the present day",
    thenLabel: "Ancient Rome",
    nowLabel: "Present Day",
    // Gladiators
    gladiatorsLabel: "The Warriors of Rome",
    gladiatorsTitle: "Gladiatorial Culture",
    gladiatorsSubtitle: "History, myth, and the reality of the arena",
    gladText: "Gladiators were not simply condemned criminals. Many were trained professionals — some even volunteers — who lived and trained in specialised schools (ludi). Different types of gladiators fought with specific equipment, and certain pairings were traditional. Historical evidence suggests that not all combats ended in death.",
    gladHeavy: "Heavy fighter",
    gladMedium: "Medium fighter",
    gladLight: "Light fighter",
    gladEquip: "Equipment",
    // Life Inside
    lifeLabel: "The Experience",
    lifeTitle: "A Day at the Colosseum",
    lifeSubtitle: "What attending a spectacle in ancient Rome may have been like",
    life1Label: "The Arrival",
    life1Title: "Enter Through Your Arch",
    life1Text: "Spectators received numbered tesserae (tokens) indicating which of the 80 arched entrances to use. The system allowed tens of thousands to find their seats with remarkable efficiency — an achievement that modern stadium designers still study.",
    life2Label: "Social Hierarchy",
    life2Title: "Take Your Place in Society",
    life2Text: "Where you sat reflected your social status. The lowest tier was reserved for senators and Vestal Virgins. Higher tiers seated equestrians and ordinary citizens. The uppermost gallery was for women and the poorest citizens.",
    life3Label: "The Atmosphere",
    life3Title: "The Crowd Gathers",
    life3Text: "Vendors sold food, drink, and programmes. The roar of the crowd was itself a form of political expression. Emperors who provided spectacular games gained public favour; those who did not risked popular discontent.",
    life4Label: "The Mechanisms",
    life4Title: "The Arena Opens",
    life4Text: "Beneath the arena floor, the hypogeum hummed with activity. At the appointed moment, trapdoors burst open and creatures, combatants, or elaborate stage sets emerged — a theatrical spectacle as much as a competitive one.",
    life5Label: "The Spectacle",
    life5Title: "The Games Begin",
    life5Text: "A full day of games typically began with animal hunts (venationes), followed by executions, and culminating in gladiatorial combats in the afternoon. The crowd's reaction could influence the fate of defeated combatants.",
    // Hypogeum
    hypoLabel: "Underground Secrets",
    hypoTitle: "The Hypogeum",
    hypoSubtitle: "The hidden machinery beneath the arena floor",
    arenaView: "Arena View",
    undergroundView: "Underground View",
    arenaViewLabel: "From Above",
    arenaViewTitle: "The Arena Floor",
    arenaViewText: "The oval arena floor measured approximately 83m × 48m. Originally covered in wooden boards topped with sand, the floor concealed the elaborate mechanical world below. Two main gates controlled the flow of spectacle.",
    portaPompa: "Porta Pompae",
    portaPompaText: "The Gate of Procession — through which gladiators and performers entered the arena in ceremonial procession.",
    portaLib: "Porta Libitinaria",
    portaLibText: "Named for Libitina, goddess of funerals — used to remove the fallen from the arena.",
    trapDoors: "Trapdoors",
    trapDoorsText: "At least 28 trapdoors in the floor connected to the lifts of the hypogeum below, enabling dramatic sudden appearances.",
    undergroundLabel: "Beneath the Arena",
    undergroundTitle: "The Underground Network",
    undergroundText: "The hypogeum was a two-level underground structure. Two central corridors and twelve side passages created a labyrinthine network. Mechanical lifts operated by counterweights could raise animals and platforms through trapdoors.",
    liftsTitle: "Mechanical Lifts",
    liftsText: "At least 28 lift shafts, operated by counterweights and capstans, could raise platforms up to 7 metres into the arena in seconds.",
    cagesTitle: "Animal Holding",
    cagesText: "Corridors included cages and pens for exotic animals — lions, tigers, bears, crocodiles, elephants — brought from across the Roman Empire.",
    sceneryTitle: "Staging & Scenery",
    sceneryText: "Entire landscape scenes could be assembled underground and raised into the arena, creating theatrical spectacles rivalling any modern stage production.",
    // Gallery
    galleryLabel: "Visual Archive",
    galleryTitle: "Gallery",
    gallerySubtitle: "Exterior · Interior · Architecture · Night · History · Details",
    filterAll: "All",
    filterExterior: "Exterior",
    filterInterior: "Interior",
    filterArch: "Architecture",
    filterHistory: "History",
    filterNight: "Night",
    gal1: "The Colosseum at Sunset",
    gal2: "Exterior Arches",
    gal3: "The Colosseum Today",
    gal4: "Ancient Glory — Historical Reconstruction",
    gal5: "Night Illumination",
    gal6: "The Hypogeum",
    gal7: "Arch Detail",
    gal8: "The Cavea — Seating Tiers",
    // Rome Map
    romeLabel: "Eternal City",
    romeTitle: "The Colosseum in the Heart of Rome",
    romeSubtitle: "Surrounded by millennia of history",
    romeText: "The Colosseum stands at the heart of Rome's archaeological zone, surrounded by some of the most significant monuments of the ancient world. The Roman Forum lies immediately to the north-west, the Palatine Hill to the south, and the Arch of Constantine stands just outside its south-east wall.",
    lm1: "Roman Forum (Foro Romano)",
    lm2: "Palatine Hill (Colle Palatino)",
    lm3: "Arch of Constantine",
    lm4: "Circo Massimo (Circus Maximus)",
    lm5: "Trevi Fountain (Fontana di Trevi)",
    lm6: "Pantheon",
    // Location
    locationLabel: "Visit",
    locationTitle: "Find the Colosseum",
    locAddress: "Address",
    locCoords: "Coordinates",
    locTransport: "Getting There",
    locCTA: "Explore on Google Maps",
    // Facts
    factsLabel: "Did You Know",
    factsTitle: "Fascinating Facts",
    fact1Title: "One of the New Seven Wonders",
    fact1Text: "The Colosseum was voted one of the New Seven Wonders of the World in 2007, alongside the Great Wall of China, Machu Picchu, and the Taj Mahal.",
    fact2Title: "Lightning-Fast Evacuation",
    fact2Text: "The system of 80 vomitoria was so efficiently designed that the Colosseum could be fully evacuated in approximately 15 minutes — admired by modern stadium designers.",
    fact3Title: "Ancient Water Spectacles?",
    fact3Text: "Some ancient sources describe naumachiae — simulated sea battles — being held in the flooded arena. Modern scholars debate whether the arena was flooded after the hypogeum was completed.",
    fact4Title: "Recycled Building Material",
    fact4Text: "During the medieval period, the Colosseum was heavily quarried. Stone was reused in St. Peter's Basilica and other buildings. Scholars estimate only about two-thirds of the original structure survives.",
    fact5Title: "A Flora All Its Own",
    fact5Text: "Over the centuries, the Colosseum developed a remarkable microecology. In the 19th century, botanists catalogued over 400 species of plants growing within the ruins.",
    fact6Title: "Capital Punishment Symbol",
    fact6Text: "Since 1999, the Colosseum is lit in gold whenever a jurisdiction abolishes capital punishment — reflecting its transformation from a site of death into a global symbol of life.",
    // Myth vs Fact
    mythLabel: "Separating History from Legend",
    mythTitle: "Myth vs. Historical Reality",
    mythSubtitle: "Click each card to reveal the historical truth",
    mythTag: "Myth",
    factTag: "Historical Reality",
    flipHint: "Click to reveal the reality",
    myth1: '"Every gladiatorial combat ended in the death of the loser."',
    fact1m: '"Many combats ended without a fatality."',
    fact1detail: "Gladiators were expensive to train. Ancient evidence suggests many fights ended when one combatant was incapacitated, with the decision to spare or kill resting with the editor and the crowd.",
    myth2: '"The ancient Romans always called it \'the Colosseum.\'"',
    fact2m: '"Its ancient name was the Flavian Amphitheatre."',
    fact2detail: "Romans called it the Amphitheatrum Flavium. The name 'Colosseum' derives from a colossal statue of Nero that stood nearby — the Colossus of Nero.",
    myth3: '"Large numbers of Christians were martyred specifically in the Colosseum."',
    fact3m: '"The historical evidence is debated and uncertain."',
    fact3detail: "While Christians were certainly persecuted in ancient Rome, direct ancient evidence for mass Christian martyrdom specifically within the Colosseum is limited and contested among modern historians.",
    myth4: '"Gladiators were slaves who were forced to fight."',
    fact4m: '"Many gladiators were volunteers seeking fame."',
    fact4detail: "While some gladiators were slaves, many were free volunteers (auctorati) who signed contracts for pay, food, and lodging. Successful gladiators became celebrities with their own fan followings.",
    // Arch Details
    detailsLabel: "Stone by Stone",
    detailsTitle: "Architectural Details",
    detailsSubtitle: "The beauty of two thousand years of stone",
    det1: "The Arches",
    det1d: "80 archways per tier · Doric, Ionic, Corinthian",
    det2: "Roman Vaults",
    det2d: "Barrel vaults in opus incertum and opus mixtum",
    det3: "Travertine Masonry",
    det3d: "~100,000 m³ quarried at Tivoli · Held without mortar",
    det4: "Engaged Columns",
    det4d: "Doric (1st) · Ionic (2nd) · Corinthian (3rd) orders",
    det5: "Corridors & Stairways",
    det5d: "Interlocking staircases leading to each tier",
    det6: "Aerial Silhouette",
    det6d: "188m × 156m · The largest amphitheatre ever built",
    // Footer
    footerTagline: '"Explore. Learn. Experience Ancient Rome."',
    footerExplore: "Explore",
    footerDiscover: "Discover",
    footerSources: "Sources & References",
    footerCopyright: "© 2024 The Colosseum — The Eternal Arena · Historical information for educational purposes",
    backToTop: "Top",
  },

  ar: {
    // Loading
    loadingTitle: "الكولوسيوم",
    loadingSubtitle: "روما، إيطاليا · الساحة الأبدية",
    // Nav
    navHome: "الرئيسية",
    navHistory: "التاريخ",
    navArchitecture: "العمارة",
    nav3D: "تجربة ثلاثية الأبعاد",
    navTimeline: "الجدول الزمني",
    navGladiators: "المصارعون",
    navGallery: "المعرض",
    navLocation: "الموقع",
    navFacts: "حقائق",
    navSubtitle: "الساحة الأبدية · روما",
    navHypogeum: "الهايبوجيوم",
    navMyth: "الأسطورة مقابل الحقيقة",
    // Hero
    heroEyebrow: "روما، إيطاليا · ٧٢–٨٠ م",
    heroSubtitle: "الأمفيتياتر الفلافي · روما",
    heroQuote: "حيث لا تزال حجارة روما تتذكر صخب التاريخ.",
    heroDesc: "أحد أكثر المعالم الأثرية الباقية شهرةً في العالم القديم — مدرّج بيضاوي بُني في عهد الإمبراطور فيسبازيان وافتُتح في عهد تيتوس، وظل رمزاً للحضارة قرابة ألفَي عام.",
    heroCTA1: "استكشف الكولوسيوم",
    heroCTA2: "ادخل التجربة ثلاثية الأبعاد",
    // Introduction
    introLabel: "المعلم",
    introTitle: "رمز روما القديمة",
    introImageLabel: "الواجهة الجنوبية",
    introText1: "الكولوسيوم — المعروف أيضاً بالأمفيتياتر الفلافي — يُعدّ من أعظم الإنجازات الهندسية في العالم القديم. أصدر الإمبراطور فيسبازيان أمراً ببنائه نحو عام ٧٢ م، وافتتحه ابنه تيتوس نحو عام ٨٠ م.",
    introText2: "استضاف هذا المبنى الضخم لعدة قرون عروضاً عامة تشمل مباريات المصارعة وصيد الحيوانات والعروض المسرحية. يُقدّر الباحثون أن طاقته الاستيعابية تتراوح بين ٥٠٬٠٠٠ و٨٠٬٠٠٠ متفرج.",
    statConstruction: "بدء البناء",
    statCapacity: "الطاقة الاستيعابية المقدّرة",
    statHeight: "الارتفاع الأصلي (تقريباً)",
    statLocation: "إيطاليا 🇮🇹",
    // History
    historyLabel: "عبر العصور",
    historyTitle: "ألفا عام من التاريخ",
    historySubtitle: "من الاستعراضات الإمبراطورية إلى المعلم الأبدي",
    era1: "البناء",
    era2: "الافتتاح",
    era3: "الاستعراضات",
    era4: "الانحدار",
    era5: "العصور الوسطى",
    era6: "العصر الحديث",
    hist1Title: "بداية الرؤية الفلافية",
    hist1Text: "أمر الإمبراطور فيسبازيان ببناء الكولوسيوم على موقع البحيرة الاصطناعية لنيرون. جمعت الهندسة الرومانية الحجر الجيري والإسفنجي والخرسانة والطوب في بناء غير مسبوق.",
    hist2Title: "تيتوس يفتتح الساحة",
    hist2Text: "افتتح الإمبراطور تيتوس الكولوسيوم بألعاب استمرت نحو مئة يوم. وأضاف الإمبراطور دوميتيان لاحقاً طابقاً رابعاً والهايبوجيوم تحت الأرض.",
    hist3Title: "عصر الاستعراضات",
    hist3Text: "لعدة قرون، استضاف الكولوسيوم مباريات المصارعة وصيد الحيوانات وعمليات الإعدام العلني. كانت هذه الأحداث متجذّرة في الحياة السياسية والاجتماعية الرومانية.",
    hist4Title: "الحريق والزلازل",
    hist4Text: "في عام ٢١٧ م، تسبّب حريق شديد في أضرار بالغة. وأحدثت الزلازل المتكررة — لا سيما في ٤٤٣ م و١٣٤٩ م — أضراراً هيكلية جسيمة.",
    hist5Title: "إعادة التوظيف عبر العصور",
    hist5Text: "بعد انتهاء ألعاب المصارعة، استُخدم الكولوسيوم مقلعاً لمواد البناء ومزاراً مسيحياً وحصناً ومسكناً في أوقات مختلفة.",
    hist6Title: "من أطلال إلى تراث عالمي",
    hist6Text: "بدءاً من القرن الثامن عشر، تنامت جهود الحفاظ عليه. قدّسه البابا بنديكتوس الرابع عشر في أربعينيات القرن الثامن عشر. واليوم يُعدّ موقعاً لليونسكو للتراث العالمي.",
    // Timeline
    timelineLabel: "التواريخ الرئيسية",
    timelineTitle: "سجل تاريخي للكولوسيوم",
    timelineSubtitle: "من حجر الأساس إلى عجيبة الدنيا",
    tl1Title: "بدء البناء",
    tl2Title: "الافتتاح الكبير",
    tl3Title: "إضافات دوميتيان",
    tl4Title: "أضرار الحريق الكبير",
    tl5Title: "تراجع الألعاب",
    tl6Title: "أضرار الزلزال",
    tl7Title: "انهيار الجدار الجنوبي",
    tl8Title: "التقديس البابوي",
    tl9Title: "موقع تراث يونسكو",
    tl10Title: "المعلم الأبدي",
    // Architecture
    archLabel: "الهيكل والهندسة",
    archTitle: "تحفة الهندسة الرومانية",
    archSubtitle: "قطعة بيضاوية من الحجر أعادت تعريف الطموح البشري",
    archClickMsg: "انقر على نقاط التفاعل المضيئة في المخطط لاستكشاف العناصر المعمارية للكولوسيوم.",
    af1Name: "الحجر الجيري الترافرتيني",
    af1Text: "استُخدم نحو ١٠٠٬٠٠٠ متر مكعب من الحجر الجيري الترافرتيني في الهيكل الخارجي، استُخرج من محاجر قرب تيفولي.",
    af2Name: "التصميم البيضاوي",
    af2Text: "أتاح الشكل البيضاوي — بأبعاد تقريبية ١٨٨ م × ١٥٦ م — رؤية واضحة للجميع ومنع المتنافسين من الاحتماء بالزوايا.",
    af3Name: "الممرات (Vomitoria)",
    af3Text: "مكّن نظام الثمانين مدخلاً المرقّماً من ملء الكولوسيوم أو إخلائه من عشرات الآلاف في نحو ١٥ دقيقة فقط.",
    af4Name: "الخرسانة الرومانية",
    af4Text: "أنتجت خرسانة Opus caementicium المدمجة مع البوزولانا البركانية هياكل بالغة المتانة. تشير الدراسات الحديثة إلى أن هذه الخرسانة ربما تزداد قوةً مع الزمن.",
    af5Name: "الأقواس العظيمة",
    af5Text: "يضم الجدار الخارجي ثلاث طبقات من ثمانين قوساً، يزيّن كل منها أعمدة مندمجة: دورية في الطابق الأول، إيونية في الثاني، وكورنثية في الثالث.",
    af6Name: "الهايبوجيوم",
    af6Text: "استخدمت الشبكة الجوفية المكوّنة من طابقين حبالاً وبكراتٍ ومنصات مفصلية لرفع الحيوانات والمتنافسين إلى الساحة بشكل مفاجئ.",
    // 3D
    threeLabel: "تجربة تفاعلية",
    threeTitle: "تجربة الكولوسيوم ثلاثية الأبعاد",
    threeSubtitle: "دوران · تكبير · استكشاف · اكتشاف",
    threeLoading: "جارٍ بناء الساحة…",
    threeExterior: "المنظر الخارجي",
    threeInterior: "المنظر الداخلي",
    threeAerial: "المنظر الجوي",
    threeReset: "إعادة الضبط",
    threeDragHint: "اسحب للدوران · مرّر للتكبير · انقر على النقاط",
    // Then & Now
    thenNowLabel: "الماضي والحاضر",
    thenNowTitle: "قديماً وحديثاً",
    thenNowSubtitle: "اسحب الفاصل لمقارنة روما القديمة باليوم",
    thenLabel: "روما القديمة",
    nowLabel: "اليوم",
    // Gladiators
    gladiatorsLabel: "محاربو روما",
    gladiatorsTitle: "ثقافة المصارعة",
    gladiatorsSubtitle: "التاريخ والأسطورة وحقيقة الساحة",
    gladText: "لم يكن المصارعون مجرد مجرمين محكوم عليهم. كان كثيرون منهم محترفين مدرّبين — بعضهم متطوعون — يعيشون ويتدربون في مدارس متخصصة. وتشير الأدلة التاريخية إلى أن النزالات لم تنتهِ دائماً بالوفاة.",
    gladHeavy: "مقاتل ثقيل",
    gladMedium: "مقاتل متوسط",
    gladLight: "مقاتل خفيف",
    gladEquip: "التجهيزات",
    // Life Inside
    lifeLabel: "التجربة",
    lifeTitle: "يوم في الكولوسيوم",
    lifeSubtitle: "كيف كانت تبدو حضور عرض في روما القديمة",
    life1Label: "الوصول",
    life1Title: "ادخل من قوسك",
    life1Text: "تلقّى المتفرجون رموزاً مرقّمة (tesserae) تشير إلى المدخل المقرّر لهم من بين الثمانين قوساً. أتاح هذا النظام لعشرات الآلاف العثور على مقاعدهم بكفاءة مذهلة.",
    life2Label: "التسلسل الاجتماعي",
    life2Title: "خذ مكانك في المجتمع",
    life2Text: "عكس مكان جلوسك وضعك الاجتماعي. خُصّصت الطبقة السفلى لمجلس الشيوخ وعذارى فيستا، وارتفعت مقاعد الطبقات الأدنى تدريجياً.",
    life3Label: "الأجواء",
    life3Title: "يجتمع الحشد",
    life3Text: "باع الباعة الطعام والشراب والبرامج. كان هدير الحشد تعبيراً سياسياً بحد ذاته. أضفت الألعاب الاستعراضية على الأباطرة شعبيةً واسعة.",
    life4Label: "الآليات",
    life4Title: "تنفتح الساحة",
    life4Text: "تحت أرضية الساحة، كان الهايبوجيوم يعمل بنشاط. في اللحظة المحددة، انفتحت الأبواب المخفية وبرزت الحيوانات والمقاتلون أو الديكورات المسرحية — استعراض مسرحي بامتياز.",
    life5Label: "العرض",
    life5Title: "تبدأ الألعاب",
    life5Text: "بدأ اليوم الكامل من الألعاب عادةً بصيد الحيوانات، ثم أحكام الإعدام، وذروته مبارزات المصارعة بعد الظهر. كان رد فعل الجمهور قادراً على تحديد مصير المنهزم.",
    // Hypogeum
    hypoLabel: "أسرار تحت الأرض",
    hypoTitle: "الهايبوجيوم",
    hypoSubtitle: "الآليات المخفية تحت أرضية الساحة",
    arenaView: "منظر الساحة",
    undergroundView: "المنظر الجوفي",
    arenaViewLabel: "من أعلى",
    arenaViewTitle: "أرضية الساحة",
    arenaViewText: "قياس الساحة البيضاوية نحو ٨٣م × ٤٨م. كانت مغطاة بألواح خشبية فوقها رمال، تخفي تحتها عالماً ميكانيكياً متطوراً. بابان رئيسيان تحكّما في تدفق العروض.",
    portaPompa: "بوابة الموكب (Porta Pompae)",
    portaPompaText: "البوابة التي دخل منها المصارعون والمؤدون في موكب احتفالي في بداية الألعاب.",
    portaLib: "بوابة المقبرة (Porta Libitinaria)",
    portaLibText: "سُمّيت باسم إلهة الجنائز ليبيتينا — استُخدمت لإخراج الضحايا من الساحة.",
    trapDoors: "الأبواب المخفية",
    trapDoorsText: "على الأقل ٢٨ باباً مخفياً في الأرضية تصل إلى مصاعد الهايبوجيوم، تتيح ظهور مفاجئاً مثيراً.",
    undergroundLabel: "تحت الساحة",
    undergroundTitle: "الشبكة تحت الأرضية",
    undergroundText: "الهايبوجيوم بنية جوفية من طابقين. ممران مركزيان واثنا عشر ممراً جانبياً خلقا شبكة متاهية. رفعت مصاعد ميكانيكية تعمل بالأثقال الموازنة حيوانات ومنصات عبر الأبواب المخفية.",
    liftsTitle: "المصاعد الميكانيكية",
    liftsText: "ما لا يقل عن ٢٨ مصعداً يعمل بالبكرات، قادراً على رفع منصات حتى ٧ أمتار في ثوانٍ.",
    cagesTitle: "حبس الحيوانات",
    cagesText: "تضمّنت الممرات أقفاصاً وحظائر لحيوانات استوائية — أسود ونمور ودببة وتماسيح وفيلة — جُلبت من أرجاء الإمبراطورية الرومانية.",
    sceneryTitle: "الإخراج والمناظر",
    sceneryText: "كان بإمكان الطاقم تركيب مناظر طبيعية كاملة تحت الأرض ورفعها إلى الساحة، لتُنتج استعراضات مسرحية تُنافس أي إنتاج حديث.",
    // Gallery
    galleryLabel: "الأرشيف البصري",
    galleryTitle: "المعرض",
    gallerySubtitle: "خارجي · داخلي · عمارة · ليلي · تاريخي · تفاصيل",
    filterAll: "الكل",
    filterExterior: "خارجي",
    filterInterior: "داخلي",
    filterArch: "العمارة",
    filterHistory: "تاريخي",
    filterNight: "ليلي",
    gal1: "الكولوسيوم عند الغروب",
    gal2: "الأقواس الخارجية",
    gal3: "الكولوسيوم اليوم",
    gal4: "المجد القديم — إعادة تصوير تاريخية",
    gal5: "الإضاءة الليلية",
    gal6: "الهايبوجيوم",
    gal7: "تفاصيل الأقواس",
    gal8: "مدرّجات الكافيا",
    // Rome Map
    romeLabel: "المدينة الأبدية",
    romeTitle: "الكولوسيوم في قلب روما",
    romeSubtitle: "محاطاً بآلاف السنين من التاريخ",
    romeText: "يقع الكولوسيوم في قلب المنطقة الأثرية لروما، محاطاً ببعض أبرز معالم العالم القديم. يقع المنتدى الروماني مباشرةً شمال غربه، وتلة بالاتين جنوبه، وقوس قسطنطين جنوب شرقه.",
    lm1: "المنتدى الروماني (Foro Romano)",
    lm2: "تلة بالاتين (Colle Palatino)",
    lm3: "قوس قسطنطين",
    lm4: "سيركو ماسيمو (Circo Massimo)",
    lm5: "نافورة تريفي (Fontana di Trevi)",
    lm6: "البانثيون",
    // Location
    locationLabel: "الزيارة",
    locationTitle: "كيف تصل إلى الكولوسيوم",
    locAddress: "العنوان",
    locCoords: "الإحداثيات",
    locTransport: "المواصلات",
    locCTA: "استكشف على خرائط جوجل",
    // Facts
    factsLabel: "هل تعلم",
    factsTitle: "حقائق مثيرة",
    fact1Title: "أحد عجائب الدنيا السبع الجديدة",
    fact1Text: "صُنّف الكولوسيوم بين عجائب الدنيا السبع الجديدة في استفتاء عالمي عام ٢٠٠٧، جنباً إلى جنب مع سور الصين العظيم وماتشو بيتشو وتاج محل.",
    fact2Title: "إخلاء بسرعة البرق",
    fact2Text: "صُمّمت الممرات الثمانون بكفاءة بالغة لدرجة أن الكولوسيوم كان يمكن إخلاؤه بالكامل في نحو ١٥ دقيقة فقط.",
    fact3Title: "معارك بحرية قديمة؟",
    fact3Text: "تصف بعض المصادر القديمة معارك بحرية مصطنعة في الساحة المغمورة بالماء. يتجادل الباحثون المعاصرون حول ما إذا حدث ذلك بعد بناء الهايبوجيوم.",
    fact4Title: "مواد بناء معاد تدويرها",
    fact4Text: "نُهب الكولوسيوم خلال العصور الوسطى لمواد البناء التي أُعيد استخدامها في كنيسة القديس بطرس وغيرها. يُقدّر الباحثون أن نحو ثلثي البنية الأصلية لا يزال قائماً.",
    fact5Title: "نظام بيئي فريد",
    fact5Text: "طوّر الكولوسيوم عبر القرون بيئةً دقيقة مذهلة. في القرن التاسع عشر، وثّق علماء النبات أكثر من ٤٠٠ نوع نباتي ينمو داخل الأطلال.",
    fact6Title: "رمز ضد عقوبة الإعدام",
    fact6Text: "منذ عام ١٩٩٩، يُضاء الكولوسيوم باللون الذهبي كلما ألغت دولة عقوبة الإعدام — تحوّلاً من موقع للموت إلى رمز عالمي للحياة.",
    // Myth vs Fact
    mythLabel: "الفصل بين التاريخ والأسطورة",
    mythTitle: "الأسطورة مقابل الحقيقة التاريخية",
    mythSubtitle: "انقر على كل بطاقة لاكتشاف الحقيقة التاريخية",
    mythTag: "أسطورة",
    factTag: "الحقيقة التاريخية",
    flipHint: "انقر لاكتشاف الحقيقة",
    myth1: '"كانت كل نزالات المصارعة تنتهي بموت الخاسر."',
    fact1m: '"كثير من النزالات انتهت دون وفاة."',
    fact1detail: "كان تدريب المصارعين مكلفاً للغاية. تُشير الأدلة القديمة إلى أن كثيراً من النزالات انتهت بعجز أحد المتنافسين، وكان قرار الإعفاء أو الإعدام بيد المنظّم والجمهور.",
    myth2: '"أطلق الرومان القدماء دائماً اسم الكولوسيوم على هذا المبنى."',
    fact2m: '"اسمه القديم هو الأمفيتياتر الفلافي."',
    fact2detail: "سمّاه الرومان Amphitheatrum Flavium نسبةً إلى الأسرة الفلافية. جاء اسم كولوسيوم في العصور الوسطى في الغالب من تمثال ضخم لنيرون كان قائماً بالقرب منه.",
    myth3: '"استُشهد أعداد كبيرة من المسيحيين تحديداً في الكولوسيوم."',
    fact3m: '"الأدلة التاريخية محلّ جدل وغير قاطعة."',
    fact3detail: "رغم أن المسيحيين تعرّضوا للاضطهاد في روما القديمة بالتأكيد، فإن الأدلة القديمة المباشرة على استشهاد جماعي مسيحي تحديداً في الكولوسيوم محدودة ومتنازع عليها.",
    myth4: '"كان المصارعون عبيداً يُكرهون على القتال."',
    fact4m: '"كثيرون من المصارعين كانوا متطوعين يسعون للشهرة."',
    fact4detail: "بينما كان بعض المصارعين عبيداً، أبرم كثيرون من الأحرار عقوداً مع مدارس المصارعة مقابل الأجر والطعام والمسكن. أصبح المصارعون الناجحون مشاهير بمتابعين من المعجبين.",
    // Arch Details
    detailsLabel: "حجراً حجراً",
    detailsTitle: "التفاصيل المعمارية",
    detailsSubtitle: "جمال ألفَي عام من الحجر",
    det1: "الأقواس",
    det1d: "٨٠ قوساً في كل طابق · دورية وإيونية وكورنثية",
    det2: "الأقبية الرومانية",
    det2d: "أقبية برميلية في Opus incertum وOpus mixtum",
    det3: "بناء الترافرتين",
    det3d: "نحو ١٠٠٬٠٠٠ م³ من محاجر تيفولي · دون ملاط",
    det4: "الأعمدة المندمجة",
    det4d: "دورية (١) · إيونية (٢) · كورنثية (٣)",
    det5: "الممرات والسلالم",
    det5d: "سلالم متشابكة تقود إلى كل طابق",
    det6: "الصورة الجوية",
    det6d: "١٨٨م × ١٥٦م · أكبر مدرّج بُني على الإطلاق",
    // Footer
    footerTagline: '"استكشف. تعلّم. عِش روما القديمة."',
    footerExplore: "استكشف",
    footerDiscover: "اكتشف",
    footerSources: "المصادر والمراجع",
    footerCopyright: "© ٢٠٢٤ الكولوسيوم — الساحة الأبدية · معلومات تاريخية للأغراض التعليمية",
    backToTop: "أعلى",
  }
};

let currentLang = localStorage.getItem('colosseum-lang') || 'en';

function switchLang(lang) {
  currentLang = lang;
  localStorage.setItem('colosseum-lang', lang);

  // Set HTML dir and lang attributes
  document.documentElement.setAttribute('lang', lang);
  document.documentElement.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');

  // Update all translatable elements
  const elements = document.querySelectorAll('[data-translate]');
  elements.forEach(el => {
    const key = el.getAttribute('data-translate');
    if (translations[lang] && translations[lang][key]) {
      // Handle special HTML entities
      el.innerHTML = translations[lang][key];
    }
  });

  // Update active lang button states
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
    btn.setAttribute('aria-pressed', btn.dataset.lang === lang ? 'true' : 'false');
  });

  // Update document title
  if (lang === 'ar') {
    document.title = 'الكولوسيوم — استكشف روما القديمة | روما، إيطاليا';
  } else {
    document.title = 'The Colosseum — Explore Ancient Rome | Rome, Italy';
  }
}

// Apply on load
document.addEventListener('DOMContentLoaded', () => {
  switchLang(currentLang);
});

// Export for inline usage
window.switchLang = switchLang;
window.translations = translations;
window.currentLang = () => currentLang;
